spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carsdb
    username: carsowner
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
